#!/usr/bin/env python3
"""Build strict Codex-compatible skill packages from SkillHub source folders."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
BUILD_MARKER = ".gaia-codex-build"


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        raise ValueError("SKILL.md 缺少 YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("SKILL.md frontmatter 未闭合")
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if value.startswith('"'):
            try:
                value = json.loads(value)
            except json.JSONDecodeError:
                pass
        meta[key.strip()] = value
    return meta, text[end + 5 :]


def build_skill(source: Path, output_root: Path) -> Path:
    meta, body = split_frontmatter((source / "SKILL.md").read_text(encoding="utf-8"))
    name = meta.get("name", "")
    description = meta.get("description", "")
    if not name or not description:
        raise ValueError(f"{source}: 缺少 name 或 description")
    target = output_root / name
    shutil.copytree(
        source,
        target,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns("README.md", "__pycache__", "*.pyc", ".DS_Store"),
    )
    strict = (
        "---\n"
        f"name: {json.dumps(name, ensure_ascii=False)}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n"
        "---\n"
        + body
    )
    (target / "SKILL.md").write_text(strict, encoding="utf-8")
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=ROOT / "dist" / "codex")
    parser.add_argument("--clean", action="store_true")
    args = parser.parse_args()
    output = args.out.resolve()
    if args.clean and output.exists():
        if output in {Path("/"), ROOT, SKILLS} or len(output.parts) < 3:
            raise SystemExit(f"拒绝清理不安全路径：{output}")
        if any(output.iterdir()) and not (output / BUILD_MARKER).is_file():
            raise SystemExit(f"拒绝清理非本工具生成的非空目录：{output}")
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / BUILD_MARKER).write_text("generated by build_codex_skills.py\n", encoding="utf-8")
    built = [build_skill(path, output) for path in sorted(SKILLS.iterdir()) if (path / "SKILL.md").is_file()]
    print(f"已生成 {len(built)} 个 Codex skill：{output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
